name: The Parenthesis
favicon: null
layout_spectrum: 0.850149845238775
typography_spectrum: 0.89361
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3784301783889532
  lightness: 0.9463735977187753
  saturation: 0.07147845276631415
  rhythmicContrast: 0.9035509433597326
purpose: []
