name: The Parenthesis
favicon: null
layout_spectrum: 0.850149845238775
typography_spectrum: 0.89361
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dd503d'
    - '#f60b06'
    - '#91bf9e'
    - '#cf725b'
    - '#b39b76'
  brandStrength: 0.625
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
