name: The Parenthesis
favicon: null
layout_spectrum: 0.01983
typography_spectrum: 0.89361
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#919191'
    - '#c3c3c3'
    - '#484848'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
